name: Test scheduler
on:
  schedule:
    - cron: "0 0 * * 1" # At 00:00 on every Monday.

  workflow_dispatch:

jobs:
  push_other_repo:
    runs-on: ubuntu-latest
    steps:
      - name: Greet
        run: echo "hello"
